**Exercise 00 Questions**

In [ ]:
#2. Create a random tensor with shape (7, 7)
tensor1 = torch.rand(7, 7)
tensor1


tensor([[0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874],
        [0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418]])

In [ ]:
#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor2 = torch.rand(1, 7)

result = torch.matmul(tensor1, tensor2.T)

print(result)
print(result.shape)

tensor([[2.3307],
        [2.2318],
        [1.2142],
        [2.2812],
        [1.3266],
        [2.0452],
        [1.7026]])
torch.Size([7, 1])


In [ ]:
# 4. Set random seed to 0 and repeat Exercises 2 & 3
torch.manual_seed(0)

tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

r = torch.matmul(tensor1, tensor2.T)
r, r.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
torch.cuda.manual_seed(1234)

In [ ]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
#  Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)

tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)

print(tensor1)
print(tensor2)

print("Device:", tensor1.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
Device: cuda:0


In [ ]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

r= torch.matmul(tensor1, tensor2.T)
r,r.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [ ]:
# 8. Find the maximum and minimum values of the output of 7.
print("Maximum:", r.max())
print("Minimum:", r.min())

Maximum: tensor(0.5617, device='cuda:0')
Minimum: tensor(0.3647, device='cuda:0')


In [ ]:
# 9.Find the maximum and minimum index values of the output of 7.
print("Maximum index:", r.argmax())
print("Minimum index:", r.argmin())

Maximum index: tensor(3, device='cuda:0')
Minimum index: tensor(0, device='cuda:0')


In [ ]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

tensor = torch.rand(size=(1, 1, 1, 10))

tensor1 = tensor1.squeeze()

print(tensor1, tensor1.shape)
print(tensor, tensor.shape)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') torch.Size([2, 3])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
