Name:Tanishka Sanjay Shirode

Batch: AIML

Day:7 (16-8-26)

In [ ]:
import math
math.sqrt(25)

5.0

In [8]:
def squareroot(n):
    root = n / 2

    for i in range(10):
        root = (root+ n / root) / 2

    return root

print(squareroot(25))

5.0


**We need python Libraries for:-**

Math calculations

data Preprocessing

Train ML models

Data Visualization

Dates and time

Databases

File Handling





In [ ]:
!pip install numpy

In [ ]:

num=[10,20,30] #Python List

**List**:  List in python stores multiple types of elements at onece not in organized way

**Array**:  Arrays in python stores only one types of elements in an organized way


In [ ]:
import numpy as np

a=np.array([10,20,30]) #Array using Numpy
print(a)

[10 20 30]


In [ ]:
numbers=[10,20,30]
result=[]
for i in numbers:
  result.append(i*2)
print(result)

[20, 40, 60]


In [ ]:
import numpy as np

a=np.array([10,20,30])
result=a*2

print(result)

[20 40 60]


In [ ]:
# Creates an arry with 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Creates an array of 5 ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Creates an array with values from 0 up to 10, with a step of 2.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:

num=np.array([10,20,30])
num[0] #Prints 0th element of the array

num[1]=99 #assigns 99 value to the 1st element of array
print(num)

[10 99 30]


In [ ]:
num=np.array([10,20,30])
num+5

#Increements each element of array by 5

array([15, 25, 35])

In [ ]:
num*2

# Multiplies each element by 2

array([20, 40, 60])

In [ ]:
num/10
# Divides each element of the array by 10

array([1., 2., 3.])

In [ ]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a+b

# Adds first element of first array and first element of second array and likewise

array([11, 22, 33])

In [ ]:
a*b
#Multiplies first element of first array with first element of second array and likewise

array([10, 40, 90])

In [ ]:
numbers=np.array([10,20,30,40,50])
np.sum(numbers)
# Returns sum of the array elements

np.int64(150)

In [ ]:
np.mean(numbers)
# Returns mean avarage of the array

np.float64(30.0)

In [ ]:
# Returns maximum element from the array
np.max(numbers)

np.int64(50)

In [ ]:
# Creates a 2D array.
numbers=np.array(([1,2,3],
[4,5,6]))
numbers.shape # Returns the shape of the array


(2, 3)

In [ ]:
# Access an element in the 2D array using row and column indices (row 0, column 1).
numbers[0,1]

np.int64(2)

In [ ]:
# Import the urllib.request module for making HTTP requests.
import urllib.request

response=urllib.request.urlopen('https://www.google.com') # Send an HTTP GET request to Google.com and store the response.
response.status # Print the HTTP status code of the response.

200

In [3]:
# Built in model urllib
import urllib.request

response=urllib.request.urlopen('https://www.google.com')
print(response)

In [ ]:
!pip install requests

We use requests third party module instead of built in urllib

because requests has a simple syntax to use than urllib

In [ ]:
# Third party module requests
import requests
requests.get('https://www.google.com')

<Response [200]>